export const AUTH_USER = "AUTH_USER";
export const AUTH_USER_FAILURE = "AUTH_USER_FAILURE";
export const LOG_OUT = "LOG_OUT";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";
export const SET_NEW_USER_NULL = "SET_NEW_USER_NULL";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
